services:
  - type: web
    name: theatre-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
