<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-stage-accent">Content management</p><h1 class="mt-1 text-2xl font-bold text-stage-text">Shows</h1></div></x-slot>
    <div class="mx-auto max-w-6xl">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 class="text-3xl font-bold text-stage-text">Productions</h2><p class="mt-2 text-stage-body">{{ $shows->count() }} {{ Str::plural('production', $shows->count()) }} in the catalogue.</p></div><a href="{{ route('admin.shows.create') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-stage-primary px-5 font-semibold text-stage-text transition hover:bg-[#4b1a98] focus:outline-none focus:ring-2 focus:ring-stage-accent focus:ring-offset-2 focus:ring-offset-stage-page">Add production</a></div>
        @if (session('status'))<div class="mt-6 rounded-xl border border-stage-teal/60 bg-stage-teal/20 p-4 text-stage-text" role="status">{{ session('status') }}</div>@endif
        <div class="mt-6 space-y-4">
            @forelse ($shows as $show)
                <article class="rounded-2xl border border-white/10 bg-stage-surface p-5 sm:p-6"><div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="text-xl font-bold text-stage-text">{{ $show->title }}</h3>@if($show->genre)<span class="rounded-full bg-stage-elevated px-3 py-1 text-xs font-medium text-stage-body">{{ $show->genre }}</span>@endif</div><p class="mt-2 text-sm text-stage-body">{{ $show->venue?->name ?? 'Venue to be announced' }} · {{ $show->start_date?->format('d M Y') ?? 'Dates TBA' }}@if($show->end_date) – {{ $show->end_date->format('d M Y') }}@endif</p><p class="mt-3 max-w-3xl text-sm leading-6 text-stage-body">{{ Str::limit($show->description, 180) }}</p></div><div class="flex shrink-0 flex-wrap gap-3"><a href="{{ route('admin.shows.edit', $show) }}" class="inline-flex min-h-10 items-center rounded-lg border border-stage-accent/70 px-4 text-sm font-semibold text-stage-accent transition hover:bg-stage-accent hover:text-stage-page focus:outline-none focus:ring-2 focus:ring-stage-accent">Edit</a><form action="{{ route('admin.shows.destroy', $show) }}" method="POST" onsubmit="return confirm('Delete {{ addslashes($show->title) }}?')">@csrf @method('DELETE')<button type="submit" class="min-h-10 rounded-lg border border-red-400/60 px-4 text-sm font-semibold text-red-200 transition hover:bg-red-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-red-300">Delete</button></form></div></div></article>
            @empty
                <div class="rounded-2xl border border-dashed border-white/20 bg-stage-surface p-10 text-center"><h3 class="text-xl font-bold text-stage-text">No productions yet</h3><p class="mt-2 text-stage-body">Start by adding the next production your community can discover.</p><a href="{{ route('admin.shows.create') }}" class="mt-5 inline-flex min-h-11 items-center rounded-xl bg-stage-primary px-5 font-semibold text-stage-text">Add production</a></div>
            @endforelse
        </div>
    </div>
</x-app-layout>
