<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-stage-accent">Places</p><h1 class="mt-1 text-2xl font-bold text-stage-text">Edit venue</h1></div></x-slot>
    <div class="mx-auto max-w-3xl"><div class="mb-6"><a href="{{ route('admin.venues.index') }}" class="text-sm font-semibold text-stage-body hover:text-stage-accent">← Back to venues</a><p class="mt-3 text-stage-body">Update practical attendance information for {{ $venue->name }}.</p></div>
        <form action="{{ route('admin.venues.update', $venue) }}" method="POST" class="space-y-6 rounded-2xl border border-[#D8CEC1] bg-stage-surface p-5 sm:p-7">@csrf @method('PUT')
            @if ($errors->any())<div class="rounded-xl border border-red-400/60 bg-red-950/30 p-4 text-red-100"><p class="font-semibold">Please fix the following:</p><ul class="mt-2 list-inside list-disc text-sm">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <div><label for="name" class="mb-2 block font-semibold text-stage-text">Venue name</label><input id="name" type="text" name="name" value="{{ old('name', $venue->name) }}" required autofocus class="min-h-11 w-full rounded-xl border-[#CFC4B6] bg-stage-page text-stage-text focus:border-stage-accent focus:ring-stage-accent"></div>
            <div><label for="address" class="mb-2 block font-semibold text-stage-text">Address</label><input id="address" type="text" name="address" value="{{ old('address', $venue->address) }}" required class="min-h-11 w-full rounded-xl border-[#CFC4B6] bg-stage-page text-stage-text focus:border-stage-accent focus:ring-stage-accent"></div>
            <div><label for="google_map_link" class="mb-2 block font-semibold text-stage-text">Google Maps link <span class="font-normal text-stage-muted">(optional)</span></label><input id="google_map_link" type="url" name="google_map_link" value="{{ old('google_map_link', $venue->google_map_link) }}" class="min-h-11 w-full rounded-xl border-[#CFC4B6] bg-stage-page text-stage-text focus:border-stage-accent focus:ring-stage-accent"></div>
            <div><label for="description" class="mb-2 block font-semibold text-stage-text">About this venue <span class="font-normal text-stage-muted">(optional)</span></label><textarea id="description" name="description" rows="5" class="w-full rounded-xl border-[#CFC4B6] bg-stage-page text-stage-text focus:border-stage-accent focus:ring-stage-accent">{{ old('description', $venue->description) }}</textarea></div>
            <div class="flex flex-col-reverse gap-3 border-t border-[#D8CEC1] pt-6 sm:flex-row sm:justify-end"><a href="{{ route('admin.venues.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-[#D8CEC1] px-5 font-semibold text-stage-text hover:bg-stage-elevated">Cancel</a><button type="submit" class="min-h-11 rounded-xl bg-stage-primary px-5 font-semibold text-white hover:bg-[#7E3D55] focus:outline-none focus:ring-2 focus:ring-stage-accent">Save changes</button></div>
        </form>
    </div>
</x-app-layout>
